name = "vhlink"
type = "javascript"
account_id = "39a76d640a29996bffbd58c36a537c2b"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "b477f3cdf6ae473cbe2a128f731b3bd1", preview_id = "b477f3cdf6ae473cbe2a128f731b3bd1" }
]
